name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
        architecture: [x64, x86, aarch64]
      fail-fast: false

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for aarch64 emulation
        if: matrix.architecture == 'aarch64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Amazon Corretto 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'
          architecture: ${{ matrix.architecture == 'x86' && 'x86' || 'x64' }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build with Gradle (x64 and x86)
        if: matrix.architecture != 'aarch64'
        run: ./gradlew clean build --stacktrace

      - name: Build with Gradle (aarch64 via QEMU)
        if: matrix.architecture == 'aarch64'
        run: |
          docker run --rm --platform linux/arm64/v8 \
          -v $(pwd):/app -w /app \
          amazoncorretto:11 \
          ./gradlew clean build --stacktrace

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
        architecture: [x64, x86, aarch64]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for aarch64 emulation
        if: matrix.architecture == 'aarch64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Amazon Corretto 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'
          architecture: ${{ matrix.architecture == 'x86' && 'x86' || 'x64' }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Run tests with Gradle (x64 and x86)
        if: matrix.architecture != 'aarch64'
        run: ./gradlew test --stacktrace

      - name: Run tests with Gradle (aarch64 via QEMU)
        if: matrix.architecture == 'aarch64'
        run: |
          docker run --rm --platform linux/arm64/v8 \
          amazoncorretto:11 \
          ./gradlew test --stacktrace

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.architecture }}
          path: build/test-results/test/